version: '2'
services:
    hellobank-app:
        image: hellobank
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hellobank-mysql:3306/hellobank?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hellobank-mysql:
        extends:
            file: mysql.yml
            service: hellobank-mysql
